import type { Category, Manufacturer, Tag } from './types';

export const DEFAULT_CATEGORIES: Omit<Category, 'id'>[] = [
  { name: 'Krajina', emoji: '🌄' },
  { name: 'Město', emoji: '🏙️' },
  { name: 'Zvířata', emoji: '🐾' },
  { name: 'Květiny', emoji: '🌸' },
  { name: 'Umění', emoji: '🎨' },
  { name: 'Fantasy', emoji: '🐉' },
  { name: 'Vánoce', emoji: '🎄' },
  { name: 'Jídlo', emoji: '🍽️' },
  { name: 'Architektura', emoji: '🏛️' },
  { name: 'Doprava', emoji: '🚂' },
  { name: 'Pohádky', emoji: '🏰' },
  { name: 'Sport', emoji: '⚽' },
  { name: 'Hudba', emoji: '🎵' },
  { name: 'Mapy', emoji: '🗺️' },
  { name: 'Moře', emoji: '🌊' },
  { name: 'Hory', emoji: '⛰️' },
  { name: 'Vesmír', emoji: '🌠' },
  { name: 'Příroda', emoji: '🌿' },
  { name: 'Historie', emoji: '📜' },
  { name: 'Věda', emoji: '🔬' },
  { name: 'Technika', emoji: '⚙️' },
  { name: 'Literatura', emoji: '📚' },
  { name: 'Film', emoji: '🎬' },
  { name: 'Mytologie', emoji: '🏺' },
  { name: 'Dinosauři', emoji: '🦕' },
  { name: 'Hmyz', emoji: '🦋' },
  { name: 'Ptáci', emoji: '🦜' },
  { name: 'Podvodní svět', emoji: '🐠' },
  { name: 'Hrady a zámky', emoji: '🏰' },
  { name: 'Zahrady', emoji: '🌺' },
  { name: 'Kočky', emoji: '🐱' },
  { name: 'Psi', emoji: '🐕' },
  { name: 'Koně', emoji: '🐎' },
  { name: 'Divoká zvěř', emoji: '🦁' },
  { name: 'Motýli', emoji: '🦋' },
  { name: 'Rostliny', emoji: '🌱' },
  { name: 'Stromy', emoji: '🌳' },
  { name: 'Ovoce', emoji: '🍎' },
  { name: 'Zelenina', emoji: '🥕' },
  { name: 'Sladkosti', emoji: '🍬' },
  { name: 'Nápoje', emoji: '🍷' },
  { name: 'Káva a čaj', emoji: '☕' },
  { name: 'Pečivo', emoji: '🥨' },
  { name: 'Mořské plody', emoji: '🦐' },
  { name: 'Sýry', emoji: '🧀' },
  { name: 'Koření', emoji: '🌶️' },
  { name: 'Bylinky', emoji: '🌿' },
  { name: 'Houby', emoji: '🍄' },
  { name: 'Lesní plody', emoji: '🫐' },
  { name: 'Farma', emoji: '🚜' },
  { name: 'Vesnice', emoji: '🏘️' },
  { name: 'Metropole', emoji: '🌆' },
  { name: 'Památky', emoji: '🗽' },
  { name: 'Mosty', emoji: '🌉' },
  { name: 'Majáky', emoji: '🏮' },
  { name: 'Mlýny', emoji: '💨' },
  { name: 'Kostely', emoji: '⛪' },
  { name: 'Mešity', emoji: '🕌' },
  { name: 'Pagody', emoji: '🏯' },
  { name: 'Paláce', emoji: '👑' },
  { name: 'Ruiny', emoji: '🏛️' },
  { name: 'Jeskyně', emoji: '🕳️' },
  { name: 'Vodopády', emoji: '🌊' },
  { name: 'Jezera', emoji: '💧' },
  { name: 'Řeky', emoji: '🌊' },
  { name: 'Ostrovy', emoji: '🏝️' },
  { name: 'Pláže', emoji: '🏖️' },
  { name: 'Pouště', emoji: '🏜️' },
  { name: 'Savany', emoji: '🦒' },
  { name: 'Džungle', emoji: '🌴' },
  { name: 'Deštné pralesy', emoji: '🌳' },
  { name: 'Tundra', emoji: '❄️' },
  { name: 'Ledovce', emoji: '🧊' }
];

export const DEFAULT_MANUFACTURERS: Omit<Manufacturer, 'id'>[] = [
  { name: 'Ravensburger', country: 'Německo', countryCode: 'DE' },
  { name: 'Trefl', country: 'Polsko', countryCode: 'PL' },
  { name: 'Clementoni', country: 'Itálie', countryCode: 'IT' },
  { name: 'Schmidt', country: 'Německo', countryCode: 'DE' },
  { name: 'Dino', country: 'Česká republika', countryCode: 'CZ' },
  { name: 'Castorland', country: 'Polsko', countryCode: 'PL' },
  { name: 'Eurographics', country: 'Kanada', countryCode: 'CA' },
  { name: 'Heye', country: 'Německo', countryCode: 'DE' },
  { name: 'Jumbo', country: 'Nizozemsko', countryCode: 'NL' },
  { name: 'Anatolian', country: 'Turecko', countryCode: 'TR' },
  { name: 'Art Puzzle', country: 'Turecko', countryCode: 'TR' },
  { name: 'Bluebird', country: 'Turecko', countryCode: 'TR' },
  { name: 'D-Toys', country: 'Rumunsko', countryCode: 'RO' },
  { name: 'Educa', country: 'Španělsko', countryCode: 'ES' },
  { name: 'Grafika', country: 'Francie', countryCode: 'FR' },
  { name: 'KS Games', country: 'Turecko', countryCode: 'TR' },
  { name: 'Piatnik', country: 'Rakousko', countryCode: 'AT' },
  { name: 'Cobble Hill', country: 'Kanada', countryCode: 'CA' },
  { name: 'Buffalo Games', country: 'USA', countryCode: 'US' },
  { name: 'New York Puzzle Company', country: 'USA', countryCode: 'US' },
  { name: 'Gibsons', country: 'Velká Británie', countryCode: 'GB' },
  { name: 'Falcon', country: 'Velká Británie', countryCode: 'GB' },
  { name: 'Pomegranate', country: 'USA', countryCode: 'US' },
  { name: 'Galison', country: 'USA', countryCode: 'US' },
  { name: 'Cloudberries', country: 'Velká Británie', countryCode: 'GB' },
  { name: 'Puzzleworks', country: 'Česká republika', countryCode: 'CZ' },
  { name: 'Piece & Love', country: 'USA', countryCode: 'US' },
  { name: 'Flame Tree Publishing', country: 'Velká Británie', countryCode: 'GB' },
  { name: 'Ricordi Arte', country: 'Itálie', countryCode: 'IT' },
  { name: 'Nathan', country: 'Francie', countryCode: 'FR' },
  { name: 'Djeco', country: 'Francie', countryCode: 'FR' },
  { name: 'Mudpuppy', country: 'USA', countryCode: 'US' },
  { name: 'eeBoo', country: 'USA', countryCode: 'US' },
  { name: 'Cavallini', country: 'USA', countryCode: 'US' },
  { name: 'Londji', country: 'Španělsko', countryCode: 'ES' },
  { name: 'Petit Collage', country: 'USA', countryCode: 'US' },
  { name: 'Janod', country: 'Francie', countryCode: 'FR' },
  { name: 'Michèle Wilson', country: 'Francie', countryCode: 'FR' },
  { name: 'Artifact Puzzles', country: 'USA', countryCode: 'US' },
  { name: 'Liberty Puzzles', country: 'USA', countryCode: 'US' },
  { name: 'Wentworth', country: 'Velká Británie', countryCode: 'GB' },
  { name: 'Nautilus Puzzles', country: 'USA', countryCode: 'US' },
  { name: 'Nervous System', country: 'USA', countryCode: 'US' },
  { name: 'Unidragon', country: 'USA', countryCode: 'US' },
  { name: 'Puzzle Michèle Wilson', country: 'Francie', countryCode: 'FR' },
  { name: 'Puzzelman', country: 'Nizozemsko', countryCode: 'NL' },
  { name: 'King International', country: 'Nizozemsko', countryCode: 'NL' },
  { name: 'Jumbo Falcon', country: 'Nizozemsko', countryCode: 'NL' },
  { name: 'Art & Fable', country: 'USA', countryCode: 'US' },
  { name: 'Bits and Pieces', country: 'USA', countryCode: 'US' }
];

export const DEFAULT_TAGS: Omit<Tag, 'id'>[] = [
  { name: 'Oblíbené', emoji: '⭐', color: '#FFD700' },
  { name: 'Náročné', emoji: '🤔', color: '#FF4444' },
  { name: 'Relaxační', emoji: '😌', color: '#4CAF50' },
  { name: 'Rodinné', emoji: '👨‍👩‍👧‍👦', color: '#2196F3' },
  { name: 'Noční skládání', emoji: '🌙', color: '#673AB7' },
  { name: 'Víkendové', emoji: '🎯', color: '#FF9800' },
  { name: 'Dovolená', emoji: '🏖️', color: '#00BCD4' },
  { name: 'Zimní', emoji: '❄️', color: '#90CAF9' },
  { name: 'Letní', emoji: '☀️', color: '#FFC107' },
  { name: 'Jarní', emoji: '🌸', color: '#E91E63' },
  { name: 'Podzimní', emoji: '🍁', color: '#795548' }
];

export const SIDEBAR_STYLES = {
  container: 'hidden md:block bg-indigo-50 dark:bg-indigo-900/10 border-r border-indigo-100 dark:border-indigo-900/20 h-[calc(100vh-4rem)] sticky top-16 transition-all duration-300 -mt-4',
  width: {
    expanded: 'w-96',
    collapsed: 'w-12'
  },
  toggleButton: 'absolute -right-3 top-4 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-full p-1 shadow-sm z-10 hover:bg-gray-50 dark:hover:bg-gray-700',
  mobileButton: 'md:hidden fixed bottom-4 right-4 z-50 bg-indigo-600 text-white p-4 rounded-full shadow-lg',
  mobileDrawer: 'md:hidden fixed inset-0 z-50 bg-gray-900/50',
  content: {
    header: 'p-4 border-b border-indigo-100 dark:border-indigo-900/20',
    body: 'flex-1 overflow-y-auto scrollbar-thin scrollbar-thumb-gray-300 dark:scrollbar-thumb-gray-600 scrollbar-track-gray-100 dark:scrollbar-track-gray-800',
    section: 'p-4 space-y-2'
  }
} as const;

export const sourceTypeConfig = {
  eshop: { label: 'E-shopy', color: 'bg-blue-100 dark:bg-blue-900/50 text-blue-800 dark:text-blue-200' },
  store: { label: 'Kamenné obchody', color: 'bg-green-100 dark:bg-green-900/50 text-green-800 dark:text-green-200' },
  person: { label: 'Osoby', color: 'bg-purple-100 dark:bg-purple-900/50 text-purple-800 dark:text-purple-200' },
  company: { label: 'Firmy', color: 'bg-orange-100 dark:bg-orange-900/50 text-orange-800 dark:text-orange-200' }
} as const;