// Kompletní seznam zemí světa v češtině s ISO kódy a emoji vlajkami
export const COUNTRIES = [
  // Evropa
  { name: 'Česká republika', code: 'CZ', flag: '🇨🇿' },
  { name: 'Německo', code: 'DE', flag: '🇩🇪' },
  { name: 'Nizozemsko', code: 'NL', flag: '🇳🇱' },
  { name: 'Polsko', code: 'PL', flag: '🇵🇱' },
  { name: 'Rakousko', code: 'AT', flag: '🇦🇹' },
  { name: 'Slovensko', code: 'SK', flag: '🇸🇰' },
  { name: 'Španělsko', code: 'ES', flag: '🇪🇸' },
  { name: 'Itálie', code: 'IT', flag: '🇮🇹' },
  { name: 'Francie', code: 'FR', flag: '🇫🇷' },
  { name: 'Velká Británie', code: 'GB', flag: '🇬🇧' },
  { name: 'Belgie', code: 'BE', flag: '🇧🇪' },
  { name: 'Dánsko', code: 'DK', flag: '🇩🇰' },
  { name: 'Finsko', code: 'FI', flag: '🇫🇮' },
  { name: 'Švédsko', code: 'SE', flag: '🇸🇪' },
  { name: 'Norsko', code: 'NO', flag: '🇳🇴' },
  { name: 'Švýcarsko', code: 'CH', flag: '🇨🇭' },
  { name: 'Portugalsko', code: 'PT', flag: '🇵🇹' },
  { name: 'Řecko', code: 'GR', flag: '🇬🇷' },
  { name: 'Bulharsko', code: 'BG', flag: '🇧🇬' },
  { name: 'Chorvatsko', code: 'HR', flag: '🇭🇷' },
  { name: 'Srbsko', code: 'RS', flag: '🇷🇸' },
  { name: 'Slovinsko', code: 'SI', flag: '🇸🇮' },
  { name: 'Estonsko', code: 'EE', flag: '🇪🇪' },
  { name: 'Lotyšsko', code: 'LV', flag: '🇱🇻' },
  { name: 'Litva', code: 'LT', flag: '🇱🇹' },
  { name: 'Rusko', code: 'RU', flag: '🇷🇺' },
  { name: 'Bělorusko', code: 'BY', flag: '🇧🇾' },
  { name: 'Ukrajina', code: 'UA', flag: '🇺🇦' },
  { name: 'Moldavsko', code: 'MD', flag: '🇲🇩' },
  { name: 'Rumunsko', code: 'RO', flag: '🇷🇴' },
  { name: 'Maďarsko', code: 'HU', flag: '🇭🇺' },
  { name: 'Albánie', code: 'AL', flag: '🇦🇱' },
  { name: 'Andorra', code: 'AD', flag: '🇦🇩' },
  { name: 'Bosna a Hercegovina', code: 'BA', flag: '🇧🇦' },
  { name: 'Černá Hora', code: 'ME', flag: '🇲🇪' },
  { name: 'Irsko', code: 'IE', flag: '🇮🇪' },
  { name: 'Island', code: 'IS', flag: '🇮🇸' },
  { name: 'Lichtenštejnsko', code: 'LI', flag: '🇱🇮' },
  { name: 'Lucembursko', code: 'LU', flag: '🇱🇺' },
  { name: 'Malta', code: 'MT', flag: '🇲🇹' },
  { name: 'Monako', code: 'MC', flag: '🇲🇨' },
  { name: 'San Marino', code: 'SM', flag: '🇸🇲' },
  { name: 'Severní Makedonie', code: 'MK', flag: '🇲🇰' },
  { name: 'Vatikán', code: 'VA', flag: '🇻🇦' },

  // Amerika
  { name: 'USA', code: 'US', flag: '🇺🇸' },
  { name: 'Kanada', code: 'CA', flag: '🇨🇦' },
  { name: 'Mexiko', code: 'MX', flag: '🇲🇽' },
  { name: 'Argentina', code: 'AR', flag: '🇦🇷' },
  { name: 'Brazílie', code: 'BR', flag: '🇧🇷' },
  { name: 'Chile', code: 'CL', flag: '🇨🇱' },
  { name: 'Kolumbie', code: 'CO', flag: '🇨🇴' },
  { name: 'Peru', code: 'PE', flag: '🇵🇪' },
  { name: 'Venezuela', code: 'VE', flag: '🇻🇪' },
  { name: 'Uruguay', code: 'UY', flag: '🇺🇾' },
  { name: 'Paraguay', code: 'PY', flag: '🇵🇾' },
  { name: 'Bolívie', code: 'BO', flag: '🇧🇴' },
  { name: 'Ekvádor', code: 'EC', flag: '🇪🇨' },
  { name: 'Guyana', code: 'GY', flag: '🇬🇾' },
  { name: 'Surinam', code: 'SR', flag: '🇸🇷' },
  { name: 'Panama', code: 'PA', flag: '🇵🇦' },
  { name: 'Kostarika', code: 'CR', flag: '🇨🇷' },
  { name: 'Nicaragua', code: 'NI', flag: '🇳🇮' },
  { name: 'Honduras', code: 'HN', flag: '🇭🇳' },
  { name: 'El Salvador', code: 'SV', flag: '🇸🇻' },
  { name: 'Guatemala', code: 'GT', flag: '🇬🇹' },
  { name: 'Belize', code: 'BZ', flag: '🇧🇿' },
  { name: 'Jamajka', code: 'JM', flag: '🇯🇲' },
  { name: 'Kuba', code: 'CU', flag: '🇨🇺' },
  { name: 'Haiti', code: 'HT', flag: '🇭🇹' },
  { name: 'Dominikánská republika', code: 'DO', flag: '🇩🇴' },

  // Asie
  { name: 'Čína', code: 'CN', flag: '🇨🇳' },
  { name: 'Japonsko', code: 'JP', flag: '🇯🇵' },
  { name: 'Jižní Korea', code: 'KR', flag: '🇰🇷' },
  { name: 'Severní Korea', code: 'KP', flag: '🇰🇵' },
  { name: 'Tchaj-wan', code: 'TW', flag: '🇹🇼' },
  { name: 'Vietnam', code: 'VN', flag: '🇻🇳' },
  { name: 'Thajsko', code: 'TH', flag: '🇹🇭' },
  { name: 'Indonésie', code: 'ID', flag: '🇮🇩' },
  { name: 'Malajsie', code: 'MY', flag: '🇲🇾' },
  { name: 'Filipíny', code: 'PH', flag: '🇵🇭' },
  { name: 'Singapur', code: 'SG', flag: '🇸🇬' },
  { name: 'Myanmar', code: 'MM', flag: '🇲🇲' },
  { name: 'Kambodža', code: 'KH', flag: '🇰🇭' },
  { name: 'Laos', code: 'LA', flag: '🇱🇦' },
  { name: 'Indie', code: 'IN', flag: '🇮🇳' },
  { name: 'Pákistán', code: 'PK', flag: '🇵🇰' },
  { name: 'Bangladéš', code: 'BD', flag: '🇧🇩' },
  { name: 'Nepál', code: 'NP', flag: '🇳🇵' },
  { name: 'Srí Lanka', code: 'LK', flag: '🇱🇰' },
  { name: 'Afghánistán', code: 'AF', flag: '🇦🇫' },
  { name: 'Írán', code: 'IR', flag: '🇮🇷' },
  { name: 'Irák', code: 'IQ', flag: '🇮🇶' },
  { name: 'Saúdská Arábie', code: 'SA', flag: '🇸🇦' },
  { name: 'Izrael', code: 'IL', flag: '🇮🇱' },
  { name: 'Turecko', code: 'TR', flag: '🇹🇷' },
  { name: 'Sýrie', code: 'SY', flag: '🇸🇾' },
  { name: 'Jordánsko', code: 'JO', flag: '🇯🇴' },
  { name: 'Libanon', code: 'LB', flag: '🇱🇧' },
  { name: 'Spojené arabské emiráty', code: 'AE', flag: '🇦🇪' },
  { name: 'Katar', code: 'QA', flag: '🇶🇦' },
  { name: 'Kuvajt', code: 'KW', flag: '🇰🇼' },
  { name: 'Bahrajn', code: 'BH', flag: '🇧🇭' },
  { name: 'Omán', code: 'OM', flag: '🇴🇲' },
  { name: 'Jemen', code: 'YE', flag: '🇾🇪' },

  // Afrika
  { name: 'Egypt', code: 'EG', flag: '🇪🇬' },
  { name: 'Jihoafrická republika', code: 'ZA', flag: '🇿🇦' },
  { name: 'Nigérie', code: 'NG', flag: '🇳🇬' },
  { name: 'Keňa', code: 'KE', flag: '🇰🇪' },
  { name: 'Etiopie', code: 'ET', flag: '🇪🇹' },
  { name: 'Ghana', code: 'GH', flag: '🇬🇭' },
  { name: 'Tanzanie', code: 'TZ', flag: '🇹🇿' },
  { name: 'Uganda', code: 'UG', flag: '🇺🇬' },
  { name: 'Angola', code: 'AO', flag: '🇦🇴' },
  { name: 'Alžírsko', code: 'DZ', flag: '🇩🇿' },
  { name: 'Maroko', code: 'MA', flag: '🇲🇦' },
  { name: 'Tunisko', code: 'TN', flag: '🇹🇳' },
  { name: 'Libye', code: 'LY', flag: '🇱🇾' },
  { name: 'Súdán', code: 'SD', flag: '🇸🇩' },
  { name: 'Jižní Súdán', code: 'SS', flag: '🇸🇸' },
  { name: 'Senegal', code: 'SN', flag: '🇸🇳' },
  { name: 'Mali', code: 'ML', flag: '🇲🇱' },
  { name: 'Pobřeží slonoviny', code: 'CI', flag: '🇨🇮' },
  { name: 'Kamerun', code: 'CM', flag: '🇨🇲' },

  // Oceánie
  { name: 'Austrálie', code: 'AU', flag: '🇦🇺' },
  { name: 'Nový Zéland', code: 'NZ', flag: '🇳🇿' },
  { name: 'Papua Nová Guinea', code: 'PG', flag: '🇵🇬' },
  { name: 'Fidži', code: 'FJ', flag: '🇫🇯' },
  { name: 'Šalamounovy ostrovy', code: 'SB', flag: '🇸🇧' },
  { name: 'Vanuatu', code: 'VU', flag: '🇻🇺' },
  { name: 'Nová Kaledonie', code: 'NC', flag: '🇳🇨' },
  { name: 'Francouzská Polynésie', code: 'PF', flag: '🇵🇫' },
  { name: 'Samoa', code: 'WS', flag: '🇼🇸' },
  { name: 'Tonga', code: 'TO', flag: '🇹🇴' }
];